name: Build all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  test_externally:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bazel: [5.0.0, last_green]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cache: "/home/runner/.cache/bazel-disk"
          - os: macos-latest
            cache: "/private/var/tmp/bazel-disk"
            bazel_extra_args: "--xcode_version_config=//.github:host_xcodes"
          - os: windows-latest
            cache: "C:\\tmp\\bazel-disk"
    name: Build all (${{ matrix.os }}, Bazel ${{ matrix.bazel }})
    env:
      BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Mount Bazel disk cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cache }}
          key: bazel-disk-cache-${{ matrix.bazel }}-${{ matrix.os }}

      - name: Build all
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
        run: bazelisk build --disk_cache=${{ matrix.cache }} ${{ matrix.bazel_extra_args }} //...

      - name: Test all
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
        run: bazelisk test --disk_cache=${{ matrix.cache }} ${{ matrix.bazel_extra_args }} //...

      - name: Print local_config_cc/BUILD
        if: ${{ always() && matrix.os == 'macos-latest' }}
        working-directory: ./tests
        run: cat $(bazelisk info output_base)/external/local_config_cc/BUILD

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: testlogs-${{ matrix.bazel}}-${{ matrix.os }}
          # https://github.com/actions/upload-artifact/issues/92#issuecomment-711107236
          path: ${{ github.workspace }}/tests/bazel-testlogs*/**/test.log
